### PR TITLE
add sonic platform

### PR DESCRIPTION
**Pull request by fire-ant**
Im having a little look at adding sonic to the list of supported platforms so I can use Boxen to stand up Sonic relatively quickly on MacOs (and anywhere else). I really like the minimalist/streamlined code here and have largely scaffolded from the PanOS material because it looks so similar. No Go expert and welcome stewarding of my ability wherever its needed!

### CODE REVIEW

**Comment by carlmontanari** [comment]
Hey @fire-ant 

Nice work! Looks like there are a few things to get sorted out, then we should be good to go.

1. We'll need to get the test "data" added... this can be sort of annoying and isn't really documented anywhere (sorry!), but TL;DR the tests will load up text output of what the devices would actually send from the `test_data` dir -- there are two types of things in here, the actual expected final output (the easy part), and the actual output the device would send. [Here](https://github.com/scrapli/scrapligo/blob/main/test_data/driver/network/sendcommand/arista_eos_session_short) is an example of the eos "short" send command session data. Basically when I set things up I enable the channel log and then steal from that and stuff that data into the test output folders. The channel log should be only what scrapli "sees" so it should slot right in.
2. Few little linter complaints to address -- `make lint` should run everything (you may need to install golangci-lint) that gets ran in CI so you can address those nits locally or of course just check the GitHub actions output. We may need to add an ignore for dupl due to the NewDriver being similar/same as eos/pan/csr/whatever.

Thanks for the work on this -- looking forward to getting sonic running in boxen too!

Carl

**Comment by fire-ant** [comment]
Fantastic, these are much appreciated. This is a passion project (though it is also adjacent to my professional interests) and I want to give it as much as I can, time permitting, all the helpful pointers are super useful. 

I've managed to get the local vm install working to the point where it reaches login and fails with the 'instance never reaches start ready state' error in the CLI. Im using debug flags to see what else is up and when I run the QEMU command (without the -display flag so I see the console as Im on a Mac) It brings up the host just fine. What's the best way of stepping through the code in your opinion? Delve debugger or something else? 

My guess is that there's something Im not seeing in the regex in using for the loop to catch the consoles up. I maybe need to vet how Boxen is actually accessing the host but I dont see it behaving any differently to OCNos in terms of being a 'not currently supported' platform. If you have ideas based on prior experience they'd be appreciated.

Will keep at it!

**Comment by carlmontanari** [comment]
> My guess is that there's something Im not seeing in the regex in using for the loop to catch the consoles up

Yep probably. If you have the BOXEN_DEV_MODE env var set with logging level at debug, boxen should be writing out the tmp directory where the build is working. Its some wonky path on Darwin like `/var/folders/2f/jcvtqld14sv7q0d59b95w3_80000gn/T/boxen1660205506/` or something like that. In there you can tail the console and any stdout/stderr output. 

You should have something similar to [this](https://github.com/carlmontanari/boxen/blob/main/boxen/platforms/ciscoxrv9k.go#L64-L66) where you are reading until "something" happens. If you elect to use the "built-in" scrapligo console thing (you probably should) and you are using that `readUntil` method, you are just reading until some output as a string. The next "initial config" phase you may or may not end up using the `ReadAndCallback` method of scrapligo, or whatever else depending on your need. 

> What's the best way of stepping through the code in your opinion? Delve debugger or something else?

TBH, I'm not super savvy w/ delve or any go debugging -- I usually just wish it was Python if I get to that point :) 

>  maybe need to vet how Boxen is actually accessing the host 

Unless you did something not "standard" it is telnet'ing to the serial port and using scrapligo, nothing too fancy, but it does suck because it is not a "normal" telnet/ssh connection, so scrapligo is set to disable auth and transport timeout so boxen can just continually read and not timeout (in this way it is much more like using paramiko than scrapli).

HTH

**Comment by carlmontanari** [comment]
Going to close this for now. I'm working on a big overhaul for scrapligo --that will make adding platforms even easier (as in just a yaml file) so if there is interest we can reopen/rediscuss after the 1.0.0 release in the next few weeks/month or two.

Carl

**Comment by fire-ant** [comment]
Thanks for letting me know. My todo list was getting bigger each week and this was getting pushed down. If you want some end user testing/feedback feel free to ping me. Happy to help the project any way I can!

**Pull request closed without merging**
