### PR TITLE
Fix goroutine leak in channel.read when transport is closed

### PR DESCRIPTION
**Pull request by mayuresh82**
addresses #107

### CODE REVIEW

**Comment by carlmontanari** [comment]
Hey @mayuresh82 !

I think off-hand this seems reasonable but I'm wondering if you could elaborate a bit on how/when this happens just so I can make sure I fully understand! I feel like "normally" we probably shouldn't hit EOF (hopefully) and even if we did we *would* want to return that error up to read to signify to the driver/user that there was an issue. Could you just elaborate a bit more on the failure/bad case here?

Thanks a bunch!
Carl

**Comment by mayuresh82** [comment]
Hey @carlmontanari  sure this issue is triggered when a netconf driver is closed. This is because when we open the netconf driver, we open the channel only ( which in turn opens the transport on the channel ):
https://github.com/scrapli/scrapligo/blob/main/driver/netconf/driver.go#L238

But when we close the driver, we only close the underlying transport on the channel:
https://github.com/scrapli/scrapligo/blob/main/driver/netconf/driver.go#L238

As a result any read calls on the transport at that point will return EOF and so the channel read() goroutine will continue to leak because at that point, there is nothing listening on the c.Errs channel:
https://github.com/scrapli/scrapligo/blob/main/driver/netconf/driver.go#L238

Perhaps the right fix for this is to close the channel instead of the transport in the netconf driver Close() method. But either way, we should still check for EOF errors for the transport as this PR does.

**Comment by carlmontanari** [comment]
@mayuresh82 thanks a bunch for the explanation. makes sense to me. I think you are also right that probably we should be actually closing the channel when calling close on the netconf driver. Its been a while since I looked at all this, but looking quickly, I think maybe closing the channel here -> https://github.com/scrapli/scrapligo/blob/main/driver/netconf/read.go#L32 makes sense. I'm traveling today but I can test that out a bit more tomorrow to see if my hunch actually works or if it breaks anything :)

**Comment by carlmontanari** [comment]
d'oh! I forgot to test yesterday :) I will remember to do that this weekend if I dont get to it before then!

**Comment by carlmontanari** [comment]
Sorry for the delay, tested and of course everything is looking good. Going to merge this then maybe play around w/ having the channel closed in that spot I linked above to see if that is a better path too. Thanks a bunch for the PRs and the patience @mayuresh82 !

**Pull request merged**
