### PR TITLE
Make channel.ReadUntilPrompt function faster

### PR DESCRIPTION
**Pull request by haccht**
Go's regular expressions are slow compared to that of python or other LL. It's because Go is using a different algorithm for regexp matching which is mentioned [here](https://awmanoj.github.io/tech/2016/09/08/on-slow-regular-expressions-golang/).
When the reponse of a specific command is long enough, the performance of the SendCommand function will be really bad. 

I have a device that has 3497511 chars of configuration, and it take more than 10 minutes when I executed `d.SendCommand('show running-config')`.
```
real    10m46.079s
user    10m49.438s
sys     0m1.042s
```

I changed ReadUntilPrompt function to wait for the prompt periodically in order to reduce the regexp match.
That improves the performance significantly.
```
real    0m52.936s
user    0m55.030s
sys     0m3.628s
```

### CODE REVIEW

**Comment by hellt** [comment]
This is the articly by Russ explaining which regexp engine rules Go uses https://swtch.com/~rsc/regexp/regexp1.html

@haccht I wonder, what will the user time be if you do the same `sh run` using scrapli python?

**Comment by hellt** [comment]
I would also provided a comment string explaining the logic of the doing stuff by every tick

**Comment by haccht** [comment]
Hi @hellt, thanks for the comment.

With the scrapli python, the performance of `show running-config` to the exact same device was as follows.
```
real    0m52.773s
user    0m5.228s
sys     0m1.490s
```

**Comment by hellt** [comment]
@haccht interesting.
I am not a perf engineer, but looks like python version spent a lot if time waiting for IO (`real` time is >> `user+sys`), while Go spent time in `user` mode.

Anyways, now with your timer-based solution they seem to match.

I have two more ideas to test (which are of general interest):
1. check if c.readDelay affects speed, by increasing it, thus reducing multiple regexp runs
2. check the time of the same command with [netmiko](https://github.com/ktbyers/netmiko)

**Comment by haccht** [comment]
@hellt
I am also not sure why Go spent so much time in `user` mode.
The default value of `c.ReadDelay` is 5 micro-seconds, and I've already tested with several time durations.

When I set `c.ReadDelay` to 1 second, the performance was:
```
real    1m3.420s
user    0m15.542s
sys     0m0.505s
```

When I set `c.ReadDelay` to 100 milli-seconds, the performance was:
```
real    0m58.466s
user    0m46.924s
sys     0m0.891s
```


I implemented same function with netmiko and the performance was:
```
real    0m55.114s
user    0m6.423s
sys     0m0.366s
```

**Comment by hellt** [comment]
thanks @haccht valuable data
I think in Go case if you're curious and have time you may want to use pprof and CPU profiler and see where program spends all this time https://www.goodwith.tech/blog/go-pprof

**Comment by haccht** [comment]
Yeah, that sounds very interesting. I would love to try pprof to investigate this behavior in my free time.

**Comment by hellt** [comment]
@haccht does this device have anything like netconf/restconf or gnmi? It would be interesting to see how much faster `sh run` retrieval would be using non scraping interface.

**Comment by haccht** [comment]
@hellt Unfortunately, my device doesn't come with netconf, restconf or gnmi while it would be quite interesting to compare the result😞

**Comment by carlmontanari** [comment]
still need to look at this this weekend, but knew there was an obvious improvement to be made as soon as I saw this thread. so that is over in #116.

its... a lot... like a lot better because it was very dumb thing I did in the first place 😁 

will check this out this weekend and see if we can combine the fixes to get any more benefits too!

thanks all!

carl

**Comment by carlmontanari** [comment]
ok, after more of @hellt excellent detective work ++ and the work that @haccht already did here, I made some more tweaks to the other branch and I think things are wayyyyyyyyyyyy better. @haccht if you could give that branch a try and let us know how that works and what you think about the changes that would be great!

**Comment by haccht** [comment]
I reviewed the changes and tried `sh run` against the same device I've checked before with that branch.
```
real    0m53.433s
user    0m3.739s
sys     0m1.337s
```

It looks all good to me! That really was great improvement. Thanks.

**Comment by carlmontanari** [comment]
Awesome, thank you for re-checking @haccht !! I think we can close this one and will get the other one merged after I am happy w/ the new test (so this doesnt happen again :p)!

**Pull request closed without merging**
